version: "3"
services:
  political-quiz-bot:
    build: .
    restart: always
    ports:
      - 443:443
    volumes:
      - ./certs:/app/certs
      - ./secret.json:/app/secret.json
      - ./data:/app/data
      - ./img-data:/app/img-data